volumes:
  postgres_data: {}

services:
  cohab-db:
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_DB=${COHAB_DB}
      - POSTGRES_PASSWORD=${COHAB_DB_PASSWORD}
      - POSTGRES_USER=${COHAB_DB_USER}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cohab-back:
    image: ghcr.io/magofrays/cohab:main
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - COHAB_DB=${COHAB_DB}
      - COHAB_DB_PASSWORD=${COHAB_DB_PASSWORD}
      - COHAB_DB_USER=${COHAB_DB_USER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRES_AT=${JWT_EXPIRES_AT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ALLOWED_METHODS=${ALLOWED_METHODS}
      - COHAB_SERVER_PORT=${COHAB_SERVER_PORT}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - SHOW_SQL=${SHOW_SQL}
    ports:
      - ${COHAB_SERVER_PORT}:${COHAB_SERVER_PORT}
    depends_on:
      - cohab-db

  cohab-front:
    build:
      context: ../CoHab-frontend/
      dockerfile: Dockerfile
      tags:
        - cohab-frontend
    image: 'cohab-frontend'
    ports:
      - ${OUTER_FRONTEND_PORT}:80
    depends_on:
      - cohab-back