volumes:
  postgres_data: {}

services:
  cohab-db:
    image: 'postgres:alpine'
    environment:
      - 'POSTGRES_DB=cohab'
      - 'POSTGRES_PASSWORD=labubu'
      - 'POSTGRES_USER=magofrays'
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cohab-back:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - cohab-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    image: 'cohab-backend'
    ports:
      - 8080:8080
    depends_on:
      - cohab-db
  cohab-front:
    build:
      context: ./frontend/cohab-app
      dockerfile: Dockerfile
      tags:
        - cohab-frontend
    image: 'cohab-frontend'
    ports:
      - 8081:80