spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  threads:
    virtual:
      enabled: true
  application:
    name: CoHab
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cohab-db:5432/${COHAB_DB}
    username: ${COHAB_DB_USER}
    password: ${COHAB_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    contexts: prod



logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL}
    by.magofrays: ${LOGGING_LEVEL}
    org.apache.kafka: WARN
server:
  port: ${COHAB_SERVER_PORT}

user:
  max-families: 5

family:
  admin-role-name: ADMIN
  admin-role-value: 100
  user-role-name: MEMBER
  user-role-value: 10
  max-member-num: 20

kafka:
  topics:
    notification: "notification"

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expires-at: ${JWT_EXPIRES_AT}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
    allowed-methods: ${ALLOWED_METHODS}
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600